# Generated by Django 5.2 on 2025-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='student_photos/')),
            ],
        ),
    ]
